  [[main]]
  name = "Posts"
  identifier = "home"
  weight = 100
  url = "/blogposts/"

  [[main]]
  name = "Tutorials"
  weight = 200
  identifier = "tutorials"
  url = "/tutorials/"

  [[main]]
  name = "Publications"
  weight = 300
  identifier = "publications"
  url = "/publications/"

  [[main]]
  name = "About me"
  weight = 400
  identifier = "about"
  url = "/about/"
