
title = "Simeon Lisovski"
author = "Simeon Lisovski"
#copyright = "2020-2021"
description = "I am a quantitative ecologist specialized in the fields of avian migration, theoretical ecology and host-pathogen interactions. My research aims to improve our understanding of the natural world and particularly how animals interact with their rapidely changing biotic and abiotic environments."
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = ["blogposts"]
#images = ["images"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
singleDateFormat = "2/1/2006"
indexDateFormat = "2/1/2006"
listDateFormat = "2/1/2006"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
# readMore = true
# postSectionName = "blog"


[simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

## Math settings
[math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[socialIcons]]
icon = "fab fa-twitter"
title = "twitter"
url = "https://twitter.com/S_Lisovski/"

[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/slisovski/"

[[socialIcons]]
icon = "fas fa-graduation-cap"
title = "Scholar"
link = "https://scholar.google.com/citations?user=3y8AwdsAAAAJ&hl=en"

[[socialIcons]]
icon = "fab fa-orcid"
title = "ORIC"
link = "https://orcid.org/0000-0002-6399-0035"

[[socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:simeon.lisovski@awi.de"